In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Customer-Churn-Records.csv")

In [3]:
#Check the dataset size
df.shape

(10000, 18)

In [3]:
#See the first records
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [6]:
#Check all columns
df.columns.tolist()

['RowNumber',
 'CustomerId',
 'Surname',
 'CreditScore',
 'Geography',
 'Gender',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Exited',
 'Complain',
 'Satisfaction Score',
 'Card Type',
 'Point Earned']

In [7]:
#Check data types
df.dtypes

RowNumber               int64
CustomerId              int64
Surname                object
CreditScore             int64
Geography              object
Gender                 object
Age                     int64
Tenure                  int64
Balance               float64
NumOfProducts           int64
HasCrCard               int64
IsActiveMember          int64
EstimatedSalary       float64
Exited                  int64
Complain                int64
Satisfaction Score      int64
Card Type              object
Point Earned            int64
dtype: object

In [8]:
#Check missing values
df.isnull().sum()

RowNumber             0
CustomerId            0
Surname               0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
dtype: int64

In [8]:
df.isnull().sum().sum()

np.int64(0)

In [9]:
#Check duplicates
df.duplicated().sum()

np.int64(0)

In [10]:
#Check unique values

print("Geography:", df["Geography"].unique())
print("Gender:", df["Gender"].unique())
print("Card Type:", df["Card Type"].unique())
print("Exited:", df["Exited"].unique())
print("IsActiveMember:", df["IsActiveMember"].unique())
print("NumOfProducts:", df["NumOfProducts"].unique())

Geography: ['France' 'Spain' 'Germany']
Gender: ['Female' 'Male']
Card Type: ['DIAMOND' 'GOLD' 'SILVER' 'PLATINUM']
Exited: [1 0]
IsActiveMember: [1 0]
NumOfProducts: [1 3 2 4]

In [11]:
#Check the churn distribution
df["Exited"].value_counts()

Exited
0    7962
1    2038
Name: count, dtype: int64

In [12]:
df["Exited"].value_counts(normalize=True) * 100

Exited
0    79.62
1    20.38
Name: proportion, dtype: float64

In [13]:
#Basic numerical summary

df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Point Earned
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203800,0.204400,3.013800,606.515100
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402842,0.403283,1.405919,225.924839
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,0.000000,1.000000,119.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,0.000000,2.000000,410.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,0.000000,3.000000,605.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000,0.000000,4.000000,801.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,1.000000,5.000000,1000.000000

In [14]:
#Age Group


df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 30, 40, 50, 60, 100],
    labels=["Under 30", "30-40", "40-50", "50-60", "60+"],
    right=False
)

In [15]:
df[["Age", "AgeGroup"]].head(10)

   Age  AgeGroup
0   42     40-50
1   41     40-50
2   42     40-50
3   39     30-40
4   43     40-50
5   44     40-50
6   50     50-60
7   29  Under 30
8   44     40-50
9   27  Under 30

In [16]:
#Create Risk Level
df["RiskLevel"] = pd.cut(
    df["RiskScore"],
    bins=[-1, 1, 3, 6],
    labels=["Low Risk", "Medium Risk", "High Risk"]
)

KeyError: 'RiskScore'

In [17]:
#Create RiskScore

df["RiskScore"] = (
    (df["IsActiveMember"] == 0).astype(int)
    + (df["Age"] >= 40).astype(int)
    + (df["CreditScore"] < 600).astype(int)
    + (df["NumOfProducts"] == 1).astype(int)
    + (df["NumOfProducts"] >= 3).astype(int)
    + (df["Balance"] == 0).astype(int)
)

In [18]:
df[["IsActiveMember", "Age", "CreditScore", "NumOfProducts", "Balance", "RiskScore"]].head(10)

   IsActiveMember  Age  CreditScore  NumOfProducts    Balance  RiskScore
0               1   42          619              1       0.00          3
1               1   41          608              1   83807.86          2
2               0   42          502              3  159660.80          4
3               0   39          699              2       0.00          2
4               1   43          850              1  125510.82          2
5               0   44          645              2  113755.78          2
6               1   50          822              2       0.00          2
7               0   29          376              4  115046.74          3
8               1   44          501              2  142051.07          2
9               1   27          684              1  134603.88          1

In [19]:
#Now create RiskLevel
df["RiskLevel"] = pd.cut(
    df["RiskScore"],
    bins=[-1, 1, 3, 6],
    labels=["Low Risk", "Medium Risk", "High Risk"]
)

In [20]:
df[["RiskScore", "RiskLevel"]].head(20)

    RiskScore    RiskLevel
0           3  Medium Risk
1           2  Medium Risk
2           4    High Risk
3           2  Medium Risk
4           2  Medium Risk
5           2  Medium Risk
6           2  Medium Risk
7           3  Medium Risk
8           2  Medium Risk
9           1     Low Risk
10          2  Medium Risk
11          3  Medium Risk
12          3  Medium Risk
13          3  Medium Risk
14          1     Low Risk
15          1     Low Risk
16          3  Medium Risk
17          2  Medium Risk
18          5    High Risk
19          1     Low Risk

In [21]:
df["RiskLevel"].value_counts()

RiskLevel
Medium Risk    6300
Low Risk       2857
High Risk       843
Name: count, dtype: int64

In [22]:
#Check whether the risk score makes sense
df.groupby("RiskLevel", observed=True)["Exited"].mean() * 100

RiskLevel
Low Risk        7.735387
Medium Risk    21.333333
High Risk      56.109134
Name: Exited, dtype: float64

In [23]:
#Create a simple customer-risk summary
risk_summary = df.groupby(
    "RiskLevel",
    observed=True
).agg(
    Customers=("CustomerId", "count"),
    Churned_Customers=("Exited", "sum"),
    Avg_Balance=("Balance", "mean")
).reset_index()

In [24]:
risk_summary["Churn_Rate"] = (
    risk_summary["Churned_Customers"]
    / risk_summary["Customers"]
) * 100

In [25]:
risk_summary

     RiskLevel  Customers  Churned_Customers   Avg_Balance  Churn_Rate
0     Low Risk       2857                221  94121.429051    7.735387
1  Medium Risk       6300               1344  72854.073917   21.333333
2    High Risk        843                473  43859.198577   56.109134

In [26]:
#Credit Score Band
df["CreditBand"] = pd.cut(
    df["CreditScore"],
    bins=[0, 600, 700, 800, 1000],
    labels=["Low", "Fair", "Good", "Excellent"],
    right=False
)

In [27]:
df[["CreditScore", "CreditBand"]].head(10)

   CreditScore CreditBand
0          619       Fair
1          608       Fair
2          502        Low
3          699       Fair
4          850  Excellent
5          645       Fair
6          822  Excellent
7          376        Low
8          501        Low
9          684       Fair

In [28]:
#Balance Segment
df["BalanceSegment"] = pd.cut(
    df["Balance"],
    bins=[-1, 1, 50000, 100000, 200000],
    labels=["Zero Balance", "Low Balance", "Medium Balance", "High Balance"]
)

In [29]:
df[["Balance", "BalanceSegment"]].head(10)

     Balance  BalanceSegment
0       0.00    Zero Balance
1   83807.86  Medium Balance
2  159660.80    High Balance
3       0.00    Zero Balance
4  125510.82    High Balance
5  113755.78    High Balance
6       0.00    Zero Balance
7  115046.74    High Balance
8  142051.07    High Balance
9  134603.88    High Balance

In [30]:
#Create Early Risk Score


df["RiskScore"] = (
    (df["IsActiveMember"] == 0).astype(int)
    + (df["Age"] >= 40).astype(int)
    + (df["CreditScore"] < 600).astype(int)
    + (df["NumOfProducts"] == 1).astype(int)
    + (df["NumOfProducts"] >= 3).astype(int)
    + (df["Balance"] == 0).astype(int)
)

In [31]:
df["RiskScore"].value_counts().sort_index()

RiskScore
0     486
1    2371
2    3805
3    2495
4     758
5      85
Name: count, dtype: int64

In [32]:
#Step 17 — Check important segments

#Let's calculate churn by the major factors.
#Geography
df.groupby("Geography")["Exited"].mean().mul(100)

Geography
France     16.174711
Germany    32.443204
Spain      16.673395
Name: Exited, dtype: float64

In [33]:
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 30, 40, 50, 60, 100],
    labels=["Under 30", "30-40", "40-50", "50-60", "60+"],
    right=False
)

In [34]:
df[["Age", "AgeGroup"]].head()

   Age AgeGroup
0   42    40-50
1   41    40-50
2   42    40-50
3   39    30-40
4   43    40-50

In [35]:
df.groupby("AgeGroup", observed=True)["Exited"].mean().mul(100)

AgeGroup
Under 30     7.556368
30-40       10.883571
40-50       30.825057
50-60       56.041427
60+         27.946768
Name: Exited, dtype: float64

In [36]:
df.to_csv("Customer_Churn_Cleaned.csv", index=False)

In [37]:
df.columns.tolist()

['RowNumber',
 'CustomerId',
 'Surname',
 'CreditScore',
 'Geography',
 'Gender',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Exited',
 'Complain',
 'Satisfaction Score',
 'Card Type',
 'Point Earned',
 'AgeGroup',
 'RiskScore',
 'RiskLevel',
 'CreditBand',
 'BalanceSegment']

In [41]:
import os

os.path.exists("Customer_Churn_Cleaned.csv")

True

In [39]:
df["BalanceSegmentOrder"] = df["BalanceSegment"].map({
    "Zero Balance": 1,
    "Low Balance": 2,
    "Medium Balance": 3,
    "High Balance": 4
})

In [42]:
df.to_csv("Customer_Churn_Cleaned.csv", index=False)

In [43]:
print(df.columns.tolist())

['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain', 'Satisfaction Score', 'Card Type', 'Point Earned', 'AgeGroup', 'RiskScore', 'RiskLevel', 'CreditBand', 'BalanceSegment', 'BalanceSegmentOrder']

In [45]:
df.to_csv("Customer_Churn_Cleaned.csv", index=False)